hospitalKonrad1/config/routes.rb
Rails.application.routes.draw do

  get 'schedules/find_schedules'
  post 'schedules/create_schedules'
  resources :appointments
  resources :schedules
  resources :doctors
  resources :profesions
  resources :patients
  resources :states
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

hospitalKonrad1/app/models/doctor.rb
class Doctor < ApplicationRecord
  belongs_to :profesion
  has_many :schedule
end

hospitalKonrad1/app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]

  # GET /doctors
  # GET /doctors.json
  def index
    @doctors = Doctor.all
  end

  # GET /doctors/1
  # GET /doctors/1.json
  def show
  end

  # GET /doctors/new
  def new
    @doctor = Doctor.new
  end

  # GET /doctors/1/edit
  def edit
  end

  # POST /doctors
  # POST /doctors.json
  def create
    @doctor = Doctor.new(doctor_params)

    respond_to do |format|
      if @doctor.save
        format.html { redirect_to @doctor, notice: 'Doctor was successfully created.' }
        format.json { render :show, status: :created, location: @doctor }
      else
        format.html { render :new }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doctors/1
  # PATCH/PUT /doctors/1.json
  def update
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to @doctor, notice: 'Doctor was successfully updated.' }
        format.json { render :show, status: :ok, location: @doctor }
      else
        format.html { render :edit }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctors/1
  # DELETE /doctors/1.json
  def destroy
    @doctor.destroy
    respond_to do |format|
      format.html { redirect_to doctors_url, notice: 'Doctor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doctor_params
      params.require(:doctor).permit(:document, :name, :lastName, :age, :phone, :email, :address, :profesion_id)
    end
end

hospitalKonrad1/app/helpers/doctors_helper.rb
module DoctorsHelper
end

hospitalKonrad1/app/views/doctors/_form.html.erb
<%= form_with(model: doctor, local: true) do |form| %>
  <% if doctor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

      <ul>
      <% doctor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :document %>
    <%= form.number_field :document %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :lastName %>
    <%= form.text_field :lastName %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.number_field :phone %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :profesion_id %>
    <%= form.text_field :profesion_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

hospitalKonrad1/app/views/doctors/edit.html.erb
<h1>Editing Doctor</h1>

<%= render 'form', doctor: @doctor %>

<%= link_to 'Show', @doctor %> |
<%= link_to 'Back', doctors_path %>

hospitalKonrad1/app/views/doctors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Doctors</h1>

<table>
  <thead>
    <tr>
      <th>Document</th>
      <th>Name</th>
      <th>Lastname</th>
      <th>Age</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Address</th>
      <th>Profesion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @doctors.each do |doctor| %>
      <tr>
        <td><%= doctor.document %></td>
        <td><%= doctor.name %></td>
        <td><%= doctor.lastName %></td>
        <td><%= doctor.age %></td>
        <td><%= doctor.phone %></td>
        <td><%= doctor.email %></td>
        <td><%= doctor.address %></td>
        <td><%= doctor.profesion %></td>
        <td><%= link_to 'Show', doctor %></td>
        <td><%= link_to 'Edit', edit_doctor_path(doctor) %></td>
        <td><%= link_to 'Destroy', doctor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Doctor', new_doctor_path %>

hospitalKonrad1/app/views/doctors/new.html.erb
<h1>New Doctor</h1>

<%= render 'form', doctor: @doctor %>

<%= link_to 'Back', doctors_path %>

hospitalKonrad1/app/views/doctors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Document:</strong>
  <%= @doctor.document %>
</p>

<p>
  <strong>Name:</strong>
  <%= @doctor.name %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @doctor.lastName %>
</p>

<p>
  <strong>Age:</strong>
  <%= @doctor.age %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @doctor.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @doctor.email %>
</p>

<p>
  <strong>Address:</strong>
  <%= @doctor.address %>
</p>

<p>
  <strong>Profesion:</strong>
  <%= @doctor.profesion %>
</p>

<%= link_to 'Edit', edit_doctor_path(@doctor) %> |
<%= link_to 'Back', doctors_path %>